// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFCorePowerTool.ggggg.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace EFCorePowerTool.ggggg
{
    public partial class GadgetstoreContext : DbContext
    {
        public GadgetstoreContext()
        {
        }

        public GadgetstoreContext(DbContextOptions<GadgetstoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<Products> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.CategoriesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PricesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductsConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
