// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EFCorePowerTool.ggggg
{
    public partial class Prices
    {
        public int ProductPriceId { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }

        public virtual Products Product { get; set; }
    }
}