// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFCorePowerTool.ggggg;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace EFCorePowerTool.ggggg.Configurations
{
    public partial class PricesConfiguration : IEntityTypeConfiguration<Prices>
    {
        public void Configure(EntityTypeBuilder<Prices> entity)
        {
            entity.HasKey(e => e.ProductPriceId);

            entity.HasIndex(e => e.ProductId, "IX_Prices_ProductId");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.Prices)
                .HasForeignKey(d => d.ProductId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Prices> entity);
    }
}
